import type { Metadata } from 'next'
import { Syncopate, Gantari } from 'next/font/google'
import { Locale, locales } from '@/i18n'
import { unstable_setRequestLocale } from 'next-intl/server'
import { cn } from '@/lib/utils'
import { Navigation } from '@/components/navigation'
import { Noise } from '@/components/noise'
import '@/styles/globals.css'

const displayFont = Syncopate({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '700'],
  variable: '--font-display',
})

const sansFont = Gantari({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-sans',
})

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }))
}

// @todo: add metadata
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export type LayoutProps = Readonly<{
  children: React.ReactNode
  params: { locale: Locale }
}>

export default function LocaleLayout({
  children,
  params: { locale },
}: LayoutProps) {
  unstable_setRequestLocale(locale)

  return (
    <html
      lang={locale}
      className={cn(displayFont.variable, sansFont.variable, 'antialiased')}
      suppressHydrationWarning
    >
      <body>
        <Noise />
        <Navigation />
        {children}
      </body>
    </html>
  )
}
